[package]
name = "tcp-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.39", features = ["net", "io-util", "rt-multi-thread", "macros"] }
clap = { version = "4.5", features = ["derive"] }
